{"version":3,"sources":["components/ConferenceCallAlert/i18n/en-US.js"],"names":["conferenceCallErrors","bringInFailed","makeConferenceFailed","terminateConferenceFailed","removeFromConferenceFailed","callIsRecording"],"mappings":";;;;;;;;;AAAA;;;;;;;;mFAGGA,+BAAqBC,a,EAAgB,6E,0CACrCD,+BAAqBE,oB,EAAuB,6E,0CAC5CF,+BAAqBG,yB,EAA4B,mF,0CACjDH,+BAAqBI,0B,EAA6B,oF,0CAClDJ,+BAAqBK,e,EAAkB,kE","sourcesContent":["import conferenceCallErrors from 'ringcentral-integration/modules/ConferenceCall/conferenceCallErrors';\n\nexport default {\n  [conferenceCallErrors.bringInFailed]: 'Failed to merge the calls due to unexpected errors. Please try again later.',\n  [conferenceCallErrors.makeConferenceFailed]: 'Failed to merge the calls due to unexpected errors. Please try again later.',\n  [conferenceCallErrors.terminateConferenceFailed]: 'Failed to hangup the conference due to unexpected errors. Please try again later.',\n  [conferenceCallErrors.removeFromConferenceFailed]: 'Failed to remove the participant due to unexpected errors. Please try again later.',\n  [conferenceCallErrors.callIsRecording]: 'Call recording in progress. Please stop recording and try again.',\n};\n"],"file":"en-US.js"}